#include "mach_both.h"
#include "../mach_inject/submodules/liblorgnette/lorgnette.c"
#include "../mach_inject/task_vaccine.c"
#include "../mach_inject/mach_injector.c"
#include "../mach_override/mach_override.c"
